### PR TITLE
add comment

### LINKED ISSUE #34: New icon animation: Add Comment
**Name of icon to be animated(as shown in [Carbon Icon Library](https://carbondesignsystem.com/guidelines/icons/library/):**
Add Comment

**Category of icon:**
Operations

**Team/product requesting:**
Carbon Icon Motion Group

**Contacts:**
 @kristastarr @johnbister

**When is this needed?**
With the second batch of icons (operations)

### PR DESCRIPTION
**Pull request by johnbister**
this closes #34

### CODE REVIEW

**Comment by silvio-hajdin** [comment]
thanks @johnbister - the + in the _Add comment_ seems to behave differently than the one in _Bookmark Add_ (which also renders cleaner and feels 'right'). Could be a browser render thing, see the video grab below:

https://user-images.githubusercontent.com/98415805/197010019-a040b07d-370c-4fc4-ac1a-37dbde40b416.mp4

**Comment by johnbister** [comment]
@silvio-hajdin this testing is so helpful! Here's what I see on my end using chrome.  My guess is that some browsers don't support vector-effect: non-scaling stroke. Let me know what browser you're using. Can you also check the zoom in and zoom out icons? I used the same vector-effect on those. We might have to try a different approach. Thank you so much! 

https://user-images.githubusercontent.com/70543333/197036909-c6e688e1-adf6-40bb-b58c-1dcc582052b8.mov

**Comment by silvio-hajdin** [comment]
totally John, same comment re:in-browser rendering as in #83 😄

**Comment by kristastarr** [comment]
Looks like there's good browser support for `vector-effect: non-scaling stroke`
https://caniuse.com/?search=vector-effect%3A%20non-scaling%20stroke

but I am definitely seeing differences between browsers.  I'll also investigate this further.

**Comment by johnbister** [comment]
@silvio-hajdin @kristastarr Let me know if the scaling stroke has been resolved on this one!

**Review by kristastarr — CHANGES_REQUESTED** [review]
The animation looks crisp in FF, Chrome, and Safari now, but in Safari, the animation is off (see screen capture).  Have you already tried using a `transform-origin`? 

https://user-images.githubusercontent.com/21047571/199123833-0bb043a1-8e6f-4d28-b1cb-0b713782bc86.mov

**Comment by johnbister** [comment]
@kristastarr good catch! I used transform-origin, but I did it by pixels. Maybe it needs to be by percentage? It gets out of whack when it's greater or less than 100 percent viewing, but looks fine at 100 percent.  Will work on it today!

**Comment by johnbister** [comment]
@kristastarr I think I fixed 'add comment' for safari. Do you mind checking and adding a review before we merge?

**Review by kristastarr — APPROVED** [review]
Yes this looks so much better in FF - per our conversation today, I will merge, and we can continue to refine later

**Pull request merged**
