### PR TITLE
add prefers-reduced-motion media query

### PR DESCRIPTION
**Pull request by kristastarr**
Addresses https://github.com/carbon-design-system/icons-motion/issues/15

**Not sure if we want to merge this yet!**

I added the `prefers-reduced-motion` media query which works for the Navigation icons.  We do have three "state change" or "toggle" type animations that we put in kind of as a demo to show future possiblities (`AddToSubtractMotion`, `MenuToCloseMotion`, `SwitcherToCloseMotion`) and they do not make sense without the motion.  Tomorrow I will modify the component code for those so that the toggle between the two icons occurs without any motion.  We could go ahead and merge this now if you guys want since it addresses most of them, or wait till I fix the last three as well.  

Or - we could remove the three toggle ones since they aren't part of Navigation. Or I can create a new section for them after I create the "Operations" section.  @johnbister what do you think? 

(Since the animations are applied to various svg elements we can't just use the svg as a parent selector, and there are no common classes so this is the best option I could think of)

### CODE REVIEW

**Comment by johnbister** [comment]
@kristastarr I think we should comment out the 3 state change icons for now and figure out our approach for them later.

**Comment by kristastarr** [comment]
@johnbister Okay! I went ahead and deleted them for now.  We can grab the code from the old repo when we're ready to include them

**Comment by johnbister** [comment]
hey! @kristastarr should we include ellipse and polyline as well in case we encounter them later?

**Review by johnbister — APPROVED** [review]
@kristastarr Looks great to me!

**Review by tw15egan — APPROVED** [review]
Not seeing any animations after enabling the `Reduce Motion` accessibility option in macOS 👍🏻 ✅ 🎉

**Comment by tay1orjones** [comment]
> Addresses https://github.com/carbon-design-system/icons-motion/issues/15

@kristastarr Unfortunately GitHub's special keywords to link issues to PRs and auto-close linked issues doesn't support the "Addresses" keyword. "Closes" works, as does [these others they list in the docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by kristastarr** [comment]
Ohhh thanks for pointing that out! 😄 I'll use one of the others in the future!

**Pull request merged**
