### PR TITLE
'Layers' and 'image search'

### LINKED ISSUE #76: New icon animation: Image search
**Name of icon to be animated as shown in [Carbon Icon Library](https://carbondesignsystem.com/guidelines/icons/library/):**
image search

**Category of icon:**
operations

**Team/product requesting:**
carbon icon motion group

**Contacts:**
@kristastarr @johnbister 

**When is this needed?**
with second set, operations

**Additional context**
* optional - is there anything else we should know?

### LINKED ISSUE #77: New icon animation: Layers
**Name of icon to be animated as shown in [Carbon Icon Library](https://carbondesignsystem.com/guidelines/icons/library/):**
Layers

**Category of icon:**
Operations

**Team/product requesting:**
carbon icon motion group

**Contacts:**
@kristastarr @johnbister 

**When is this needed?**
with second set, operations

**Additional context**
similar to collapse all--follow same specs

### PR DESCRIPTION
**Pull request by johnbister**
this closes #77 

this closes #76 

sorry to lump these together. i forgot to make a new branch

### CODE REVIEW

**Comment by kristastarr** [comment]
Also seeing browser inconsistencies on this one... both are crisp in Safari; `Layers` is crisp but `Image search` is a bit fuzzy in Chrome and FF.  Let's hold off on merging this one until we sort out the problem since it's impacting multiple other icons

**Review by kristastarr — COMMENTED** [review]
Also seeing browser inconsistencies on this one... both are crisp in Safari; Layers is crisp but Image search is a bit fuzzy in Chrome and FF. Let's hold off on merging this one until we sort out the problem since it's impacting multiple other icons

**Review by kristastarr — APPROVED** [review]
@johnbister The animations look good in Chrome, FF, and Safari today... I'm not sure what was causing the issue before?? Should I go ahead and merge these?

**Comment by johnbister** [comment]
They look OK to me too! I think they're OK to merge

**Pull request merged**
