### PR TITLE
add connect icon

### LINKED ISSUE #72: New icon animation: Connect
**Name of icon to be animated as shown in [Carbon Icon Library](https://carbondesignsystem.com/guidelines/icons/library/):**
connect

**Category of icon:**
operations

**Team/product requesting:**
carbon icon motion group

**Contacts:**
@kristastarr @johnbister 

**When is this needed?**
with second set of icons, operations

**Additional context**
* optional - is there anything else we should know?

### PR DESCRIPTION
**Pull request by johnbister**
this closes #72

### CODE REVIEW

**Comment by silvio-hajdin** [comment]
thanks @johnbister - regrettably some 'pixel chewing' and clipping on top of the outlined circle is happening on my end, always tough with animating non-linear shapes:

https://user-images.githubusercontent.com/98415805/197011103-1089b15c-11ae-493d-8bcb-2552311f43e5.mov

**Comment by johnbister** [comment]
Thanks for sending @silvio-hajdin -- Weird! I'm not seeing anything on my end. What browser are you using? Is this on an external monitor? Do you know the resolution and hertz? I'm trying to recreate some of the artifacts you keep getting. Any info you can provide would be helpful. Thanks again! :smiley:

**Comment by johnbister** [comment]
https://user-images.githubusercontent.com/70543333/197036039-466278ce-44f3-4c6e-9d10-2f3e6550c28a.mov

Here's what I see.

**Comment by silvio-hajdin** [comment]
totally John, I can definitely see how browser/render engine variances will affect the appearance here. I use the latest Firefox (currently 106.0.1 / 64-bit) on macOS Monterey 12.6, on an ultra-wide Asus monitor in its native 3440x1440 res (and a very decent monitor at that, nice tight small dot pitch and no corner distortions of any kind). 

It's positively a FF vs Chrome vs Safari issue, and something we'll need to continuously keep an eye on. FF shows most of this reported artifacting, Chrome is better (albeit with some softening/anti-aliasing happening on faster-animating objects), and Safari is about the best (with only minor or no issues).

**Review by kristastarr — APPROVED** [review]
The animations look crisp now in Chrome, FF, and Safari.  @johnbister It doesn't look like you made any changes so not sure why it's working now and it wasn't before? Anyone opposed to me merging?

**Comment by johnbister** [comment]
@kristastarr same here. Maybe a little anti-aliasing in FF but I really have to squint and I don't think it's a deal breaker. I'm OK with merging this icon and keeping an eye out as we merge more icons. I can resolve the conflicts and merge if you want.

**Pull request merged**
